# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teleop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'teleop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cteleop.proto\x12\x15interlatent.teleop.v1\"~\n\x0cTeleopTarget\x12\x19\n\x11\x63ontrol_timestamp\x18\x01 \x01(\x04\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x15\n\rjoint_targets\x18\x03 \x03(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x16\n\x0e\x64\x65\x61\x64man_active\x18\x05 \x01(\x08\"\x85\x01\n\tTeleopAck\x12\x19\n\x11\x63ontrol_timestamp\x18\x01 \x01(\x04\x12\x1b\n\x13server_timestamp_ns\x18\x02 \x01(\x04\x12\x16\n\x0e\x63urrent_joints\x18\x03 \x03(\x02\x12\x10\n\x08\x65stopped\x18\x04 \x01(\x08\x12\x16\n\x0estatus_message\x18\x05 \x01(\t\"c\n\x11OpenTeleopRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x12\n\ncontrol_hz\x18\x03 \x01(\r\x12\x15\n\rsession_token\x18\x04 \x01(\t\"\xa2\x01\n\x12OpenTeleopResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ncontrol_hz\x18\x02 \x01(\r\x12\x13\n\x0bjoint_names\x18\x03 \x03(\t\x12\x11\n\tjoint_min\x18\x04 \x03(\x02\x12\x11\n\tjoint_max\x18\x05 \x03(\x02\x12\x13\n\x0bhome_joints\x18\x06 \x03(\x02\x12\x14\n\x0cmax_velocity\x18\x07 \x03(\x02\"(\n\x12\x43loseTeleopRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x15\n\x13\x43loseTeleopResponse2\xad\x02\n\rTeleopService\x12\x61\n\nOpenTeleop\x12(.interlatent.teleop.v1.OpenTeleopRequest\x1a).interlatent.teleop.v1.OpenTeleopResponse\x12S\n\x06Stream\x12#.interlatent.teleop.v1.TeleopTarget\x1a .interlatent.teleop.v1.TeleopAck(\x01\x30\x01\x12\x64\n\x0b\x43loseTeleop\x12).interlatent.teleop.v1.CloseTeleopRequest\x1a*.interlatent.teleop.v1.CloseTeleopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teleop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEOPTARGET']._serialized_start=39
  _globals['_TELEOPTARGET']._serialized_end=165
  _globals['_TELEOPACK']._serialized_start=168
  _globals['_TELEOPACK']._serialized_end=301
  _globals['_OPENTELEOPREQUEST']._serialized_start=303
  _globals['_OPENTELEOPREQUEST']._serialized_end=402
  _globals['_OPENTELEOPRESPONSE']._serialized_start=405
  _globals['_OPENTELEOPRESPONSE']._serialized_end=567
  _globals['_CLOSETELEOPREQUEST']._serialized_start=569
  _globals['_CLOSETELEOPREQUEST']._serialized_end=609
  _globals['_CLOSETELEOPRESPONSE']._serialized_start=611
  _globals['_CLOSETELEOPRESPONSE']._serialized_end=632
  _globals['_TELEOPSERVICE']._serialized_start=635
  _globals['_TELEOPSERVICE']._serialized_end=936
# @@protoc_insertion_point(module_scope)
