# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import teleop_pb2 as teleop__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in teleop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TeleopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenTeleop = channel.unary_unary(
                '/interlatent.teleop.v1.TeleopService/OpenTeleop',
                request_serializer=teleop__pb2.OpenTeleopRequest.SerializeToString,
                response_deserializer=teleop__pb2.OpenTeleopResponse.FromString)
        self.Stream = channel.stream_stream(
                '/interlatent.teleop.v1.TeleopService/Stream',
                request_serializer=teleop__pb2.TeleopTarget.SerializeToString,
                response_deserializer=teleop__pb2.TeleopAck.FromString)
        self.CloseTeleop = channel.unary_unary(
                '/interlatent.teleop.v1.TeleopService/CloseTeleop',
                request_serializer=teleop__pb2.CloseTeleopRequest.SerializeToString,
                response_deserializer=teleop__pb2.CloseTeleopResponse.FromString)


class TeleopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenTeleop(self, request, context):
        """One-time handshake: returns joint schema + safety envelope so the
        producer can construct correct TeleopTargets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """Bidirectional control stream. Producer pushes TeleopTarget at its
        own rate; Pi emits TeleopAck at control rate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseTeleop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeleopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenTeleop': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenTeleop,
                    request_deserializer=teleop__pb2.OpenTeleopRequest.FromString,
                    response_serializer=teleop__pb2.OpenTeleopResponse.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=teleop__pb2.TeleopTarget.FromString,
                    response_serializer=teleop__pb2.TeleopAck.SerializeToString,
            ),
            'CloseTeleop': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseTeleop,
                    request_deserializer=teleop__pb2.CloseTeleopRequest.FromString,
                    response_serializer=teleop__pb2.CloseTeleopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interlatent.teleop.v1.TeleopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interlatent.teleop.v1.TeleopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeleopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenTeleop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.teleop.v1.TeleopService/OpenTeleop',
            teleop__pb2.OpenTeleopRequest.SerializeToString,
            teleop__pb2.OpenTeleopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/interlatent.teleop.v1.TeleopService/Stream',
            teleop__pb2.TeleopTarget.SerializeToString,
            teleop__pb2.TeleopAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def CloseTeleop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.teleop.v1.TeleopService/CloseTeleop',
            teleop__pb2.CloseTeleopRequest.SerializeToString,
            teleop__pb2.CloseTeleopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
