# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.unary_unary(
                '/interlatent.inference.v1.InferenceService/OpenSession',
                request_serializer=messages__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=messages__pb2.OpenSessionResponse.FromString)
        self.Stream = channel.stream_stream(
                '/interlatent.inference.v1.InferenceService/Stream',
                request_serializer=messages__pb2.Observation.SerializeToString,
                response_deserializer=messages__pb2.ActionChunk.FromString)
        self.Infer = channel.unary_unary(
                '/interlatent.inference.v1.InferenceService/Infer',
                request_serializer=messages__pb2.Observation.SerializeToString,
                response_deserializer=messages__pb2.ActionChunk.FromString)
        self.RecordTick = channel.unary_unary(
                '/interlatent.inference.v1.InferenceService/RecordTick',
                request_serializer=messages__pb2.RecordTickRequest.SerializeToString,
                response_deserializer=messages__pb2.RecordTickResponse.FromString)
        self.RecordTicks = channel.unary_unary(
                '/interlatent.inference.v1.InferenceService/RecordTicks',
                request_serializer=messages__pb2.RecordTicksRequest.SerializeToString,
                response_deserializer=messages__pb2.RecordTicksResponse.FromString)
        self.CloseSession = channel.unary_unary(
                '/interlatent.inference.v1.InferenceService/CloseSession',
                request_serializer=messages__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=messages__pb2.CloseSessionResponse.FromString)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """Bidirectional stream so the robot can pipeline observations and
        the server can push action chunks back as soon as they're ready.
        Client may also use unary Infer (below) over gRPC-Web where
        bidi-stream is awkward.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Unary fallback for gRPC-Web / simpler clients.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTick(self, request, context):
        """Stream per-tick captures (obs + executed action + JPEGs) into the
        server's recorder. Decoupled from Infer so the recorder gets every
        control tick instead of just the ones where Infer happened to fire.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTicks(self, request, context):
        """Batched RecordTick. The client's recorder drain coalesces queued
        ticks and ships them in one RPC to keep the remote link from
        becoming the capture bottleneck. Falls back to unary RecordTick
        against servers that predate this method.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=messages__pb2.OpenSessionRequest.FromString,
                    response_serializer=messages__pb2.OpenSessionResponse.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=messages__pb2.Observation.FromString,
                    response_serializer=messages__pb2.ActionChunk.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=messages__pb2.Observation.FromString,
                    response_serializer=messages__pb2.ActionChunk.SerializeToString,
            ),
            'RecordTick': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTick,
                    request_deserializer=messages__pb2.RecordTickRequest.FromString,
                    response_serializer=messages__pb2.RecordTickResponse.SerializeToString,
            ),
            'RecordTicks': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTicks,
                    request_deserializer=messages__pb2.RecordTicksRequest.FromString,
                    response_serializer=messages__pb2.RecordTicksResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=messages__pb2.CloseSessionRequest.FromString,
                    response_serializer=messages__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interlatent.inference.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interlatent.inference.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.inference.v1.InferenceService/OpenSession',
            messages__pb2.OpenSessionRequest.SerializeToString,
            messages__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/interlatent.inference.v1.InferenceService/Stream',
            messages__pb2.Observation.SerializeToString,
            messages__pb2.ActionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.inference.v1.InferenceService/Infer',
            messages__pb2.Observation.SerializeToString,
            messages__pb2.ActionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def RecordTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.inference.v1.InferenceService/RecordTick',
            messages__pb2.RecordTickRequest.SerializeToString,
            messages__pb2.RecordTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def RecordTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.inference.v1.InferenceService/RecordTicks',
            messages__pb2.RecordTicksRequest.SerializeToString,
            messages__pb2.RecordTicksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interlatent.inference.v1.InferenceService/CloseSession',
            messages__pb2.CloseSessionRequest.SerializeToString,
            messages__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
