#!/usr/bin/env python3
"""Dev-time helper: print URDF-derived joint limits for a dimos RobotProfile.

Usage (requires the ``[dimos]`` extra installed — this script is never
imported by any runtime path, so it does not weaken robot_profile.py's
"importable without dimos" invariant, tested by tests/test_dimos_config.py):

    python packages/sdk/scripts/dimos_profile_gen.py \\
        --urdf /path/to/A1Z_G1Z.urdf \\
        --joint arm_joint1 --joint arm_joint2 --joint arm_joint3 \\
        --joint arm_joint4 --joint arm_joint5 --joint arm_joint6

Prints, for each ``--joint`` (in the order given — must match the kind's
profile joint order, arm joints only; the gripper is never in the URDF and
must still be hand-declared), one ``(lower, upper),`` line to transcribe into
the kind's ``adapters/dimos/robots/<kind>.toml`` ``[profile]`` limits, plus the
raw URDF ``velocity_limit`` and ``effort_limit`` as commented-out reference
values.

This tool intentionally does NOT emit a ``max_velocity`` or ``rest_pose``
tuple: per this project's stated philosophy (see the xarm7/a1z TOML comments
on why a URDF's raw caps are not trustworthy), a URDF's velocity_limit is
typically a motor max rather
than a safe per-tick streaming cap, and a rest pose is not declared in a URDF
at all — both remain deliberate human judgment calls, reviewed and committed
as static literals same as today, not auto-derived.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _parse_package_path(value: str) -> tuple[str, Path]:
    name, _, path = value.partition("=")
    if not path:
        raise argparse.ArgumentTypeError(
            f"expected NAME=PATH, got {value!r}"
        )
    return name, Path(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", required=True, help="Path to a .urdf/.xacro/.xml file")
    parser.add_argument(
        "--joint",
        action="append",
        dest="joints",
        required=True,
        help="Joint name to look up (repeatable, in profile order)",
    )
    parser.add_argument(
        "--package-path",
        action="append",
        dest="package_paths",
        type=_parse_package_path,
        default=[],
        metavar="NAME=PATH",
        help="xacro package_paths entry (repeatable), needed for xacro $(find ...) resolution",
    )
    args = parser.parse_args(argv)

    try:
        from dimos.robot.model_parser import parse_model
    except ImportError as exc:
        print(
            "this script requires dimos installed (pip install 'interlatent[dimos]'): "
            f"{exc}",
            file=sys.stderr,
        )
        return 1

    package_paths = dict(args.package_paths) or None
    model = parse_model(Path(args.urdf), package_paths=package_paths)

    missing = [name for name in args.joints if model.get_joint(name) is None]
    if missing:
        available = sorted(j.name for j in model.actuated_joints)
        print(
            f"joint(s) not found in {args.urdf}: {missing}\n"
            f"actuated joints in the file: {available}",
            file=sys.stderr,
        )
        return 1

    print("# Generated by dimos_profile_gen.py from", args.urdf)
    print("# Review before pasting into robot_profile.py -- see module docstring.")
    for name in args.joints:
        j = model.get_joint(name)
        assert j is not None  # narrowed by the missing-joint check above
        print(
            f"    ({j.lower_limit}, {j.upper_limit}),".ljust(28)
            + f"# {name}  (URDF velocity_limit={j.velocity_limit}, "
            f"effort_limit={j.effort_limit})"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
